/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;


/**
 *
 * @author MiguelÁngel
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setTitle("Diputados de Estados Unidos");
        setLocationRelativeTo(null);
        setResizable(false);
        VistaLegislatura visLeg = new VistaLegislatura();
        VistaDiputado visDip = new VistaDiputado();
        VistaEvento visEve = new VistaEvento();
        VistaVotacion visVot = new VistaVotacion();
        VistaResultado visRes = new VistaResultado();
        VistaInformacion visInf = new VistaInformacion();
        jTabbedPane1.add("Legislaturas", visLeg);
        jTabbedPane1.setIconAt(0, new ImageIcon(getClass().getResource("/vista/imagenes/iconos/iconLegislatura30x30.png")));
        jTabbedPane1.add("Diputados", visDip);
        jTabbedPane1.setIconAt(1, new ImageIcon(getClass().getResource("/vista/imagenes/iconos/iconDiputado30x30.png")));
        jTabbedPane1.add("Eventos", visEve);
        jTabbedPane1.setIconAt(2, new ImageIcon(getClass().getResource("/vista/imagenes/iconos/iconEvento30x30.png")));
        jTabbedPane1.add("Votaciones", visVot);
        jTabbedPane1.setIconAt(3, new ImageIcon(getClass().getResource("/vista/imagenes/iconos/iconVotacion30x30.png")));
        jTabbedPane1.add("Resultados", visRes);
        jTabbedPane1.setIconAt(4, new ImageIcon(getClass().getResource("/vista/imagenes/iconos/iconResultado30x30.png")));
        jTabbedPane1.add("Informacion", visInf);
        jTabbedPane1.setIconAt(5, new ImageIcon(getClass().getResource("/vista/imagenes/iconos/iconInformacion30x30.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jPanelRotuloPrincipal = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diputados de Estados Unidos");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelRotuloPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelRotuloPrincipalLayout = new javax.swing.GroupLayout(jPanelRotuloPrincipal);
        jPanelRotuloPrincipal.setLayout(jPanelRotuloPrincipalLayout);
        jPanelRotuloPrincipalLayout.setHorizontalGroup(
            jPanelRotuloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRotuloPrincipalLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRotuloPrincipalLayout.setVerticalGroup(
            jPanelRotuloPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRotuloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRotuloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelRotuloPrincipal;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
